#!/bin/bash

if [ "${DEBUG}" = "ON" ]; then
 set -x
fi

# This shell program will allow sed to 
#  run recursively for a particular 
#  substitution.
# Print first then replace. Life is good.
# If a non-recursive method is sought, 
#  just use sed.
# usage: subrec <-h | -p | --replace> <original regex> <replacement regex> <directory>

flag="$1"
orig="$2"
repl="$3"
dir="$4"

function usesed () {
 
 cd ${dir:=/home}

 for file in `ls`; do

  if [ -d ${file} ]; then
   echo "RECURSING INTO ${file}..."
   $0 ${flag} "${orig}" "${repl}" ${file}
   continue
  fi

  if [ "${flag}" == "-p" ]; then
   sed -n "s/${orig}/${repl}/gp" ${file}
  elif [ "${flag}" == "--replace" ]; then
   sed -i "s/${orig}/${repl}/g" ${file}
  fi
 
 done

}

if [ "${flag}" == "-h" ]; then
 echo `basename $0` ": flag  original_string  replacement_string  directory"
 exit 0;
fi

usesed
